### ISSUE TITLE
Question about DoctorNet for CiFar10

### ISSUE THREAD

**Issue by hongxin001** [Newbeeer/Max-MIG#2]
I found that in the model of DoctorNet for CIFAR10, you don't use self.classifier in forward function. But for other datasets, you use it. Is this correct or just missing?

```
class left_neural_net_dn(nn.Module):
    """
    left neural net for Docter Net method
    """
    def __init__(self):
        super(left_neural_net_dn, self).__init__()
        for i in range(Config.expert_num):
            m_name = "dn" + str(i+1)
            self.add_module(m_name,nn.Linear(512, Config.num_classes))
        self.vgg = VGG('VGG16')
        self.features = self.vgg.features
        self.classifier = self.vgg.classifier
    def forward(self, x):
        x = self.features(x)
        x = x.view(-1, 512)
        out = F.log_softmax(self.dn1(x),1).unsqueeze(0)
        for name, module in self.named_children():
            if name[0:2] != 'dn' or name == 'dn1':
                continue
            out = torch.cat((out,F.log_softmax(module(x), 1).unsqueeze(0)),0)
        return out
```

**Comment by Newbeeer** [comment]
Hi,

The code is correct. In the doctor net architecture we need to model every expert with a MLP, which is a classifier. We use self.dni() (1<=i<= expert_num) to act as classifiers.

**Comment by Newbeeer** [comment]
Thanks for the correction. I will delete the redundant codes.

**Comment by hongxin001** [comment]
> Thanks for the correction. I will delete the redundant codes.

I think it's not a mistake about redundant code. I mean, in other datasets, you used the classifier, which I think is a mistake.
