### ISSUE TITLE
The code need a file named prepared, but the project don't have.

### ISSUE THREAD

**Issue by supermy777** [Newbeeer/Max-MIG#4]
if train:
        path = './prepared/'

        data_train_vgg16 = load_data(path + "data_train_vgg16.npy").transpose(0, 3, 1, 2)

**Comment by Newbeeer** [comment]
Hi, 

The file belongs to the Labelme dataset and can be found at [http://fprodrigues.com//deep_LabelMe.tar.gz](http://fprodrigues.com//deep_LabelMe.tar.gz). Sorry for the huge delay and inconvenience.
